import "@radix-ui/themes/styles.css";
import "@/styles/globals.scss";

import type { Metadata } from "next";
import { Theme } from "@radix-ui/themes";
import AuthProvider from "./auth-provider";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <AuthProvider>
          <Theme accentColor="teal" grayColor="mauve" scaling="110%" >
            {children}
          </Theme>
        </AuthProvider>
      </body>
    </html>
  );
}
